language: python
python:
  - "3.6.10"      # current default Python on Travis CI
# command to install dependencies
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - python setup.py install
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -n is_test python==3.6.10 -y
  - conda activate is_test
  - pip install .[testing]
  - conda install py-xgboost -y
# command to run tests
script: pytest --cov=./
after_success:
  - bash <(curl -s https://codecov.io/bash) -t # submit coverage
